version: '3.7'
services:
  zabbix-epics:
    image: itorafael/zabbix-epics:latest
    #image: lnlscon/zabbix-epics:v0.2.3
    volumes:
      - /storage/services/repository/zabbix-epics:/opt/zabbix-epics
    #ports:
    #  - "10050"    # Zabbix agent
    #  - "10051"    # Zabbix trapper
    networks:
      hostnet: {}
    dns:
      - 10.128.255.7
      - 10.0.0.71
      - 10.0.0.72
    deploy:
      placement:
        constraints:
          - node.hostname != TA-TiRack-CO-FWSrv-1
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  hostnet:
    external: true
    name: host
